# Generated by Django 5.1.4 on 2025-01-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInitialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_port', models.IntegerField()),
                ('device_api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('wattage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('wattage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
