# Generated by Django 5.1.4 on 2025-01-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devicestatus',
            table='devicestatus',
        ),
        migrations.AlterModelTable(
            name='energyusage',
            table='energy_usage',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
        migrations.AlterModelTable(
            name='switch',
            table='switches',
        ),
    ]
