# Generated by Django 5.1.4 on 2025-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecox', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='power_controls',
            field=models.CharField(help_text="The power control settings of the switch (e.g., 'dim' or 'bright')", max_length=15),
        ),
        migrations.AlterField(
            model_name='switch',
            name='state',
            field=models.BooleanField(default=False, help_text='The current state of the switch (ON/OFF)'),
        ),
    ]
